# Generated by Django 3.0.5 on 2020-04-17 14:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, default='', max_length=500)),
                ('product_code', models.CharField(blank=True, default='', max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model_name', models.CharField(blank=True, default='', max_length=200)),
                ('release', models.CharField(choices=[('gr', 'General Release'), ('collab', 'Collaboration')], default='gr', max_length=50)),
                ('sneaker_type', models.CharField(choices=[('LIFESTYLE', 'Lifestyle'), ('READYTOWEAR', 'Ready-to-Wear'), ('CASUAL', 'Casual'), ('BOOTS', 'Boots'), ('RUNNING', 'Running'), ('OUTDOOR', 'Outdoor'), ('TRAINING', 'Training'), ('FOOTBALL', 'Football'), ('BASKETBALL', 'Basketball'), ('TENNIS', 'Tennis'), ('GOLF', 'Golf'), ('RUGBY', 'Rugby'), ('WEIGHTLIFTING', 'Weightlifting'), ('RUGBY', 'Rugby'), ('SKATEBOARDING', 'Skateboarding')], default='', max_length=50)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('retail_price', models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('purchase_price', models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('collection', models.CharField(blank=True, default='', max_length=200)),
                ('date_of_last_use', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sneaker', to='freshSneakers.Sneaker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
